homepage/urls.py
from django.contrib import admin
from django.urls import include, path
from personal_website.views import readiness_check
from utils.views import readiness_check_view


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('personal_website.urls', namespace='personal_website')),
    path('csp/', include('csp.urls', namespace='csp')),
    path('myfinance50/', include([
        path('', include(('brokerage.urls', 'brokerage'), namespace='brokerage')),
        path('', include(('users.urls', 'users'), namespace='users')),
    ])),
    path('readiness_check/', readiness_check, name='readiness_check'),
    path('utils/', include('utils.urls', namespace='utils')),
]

personal_website/urls.py
from django.urls import include, path
from django.shortcuts import redirect
from django.views.generic import TemplateView
from . import views
from .views import fetch_substack_rss

# Defines application's namespace (set in project's urls.py file)
app_name = 'personal_website'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('contact/', views.contact_view, name='contact'),
    #path('csp/', include('csp.urls', namespace='csp')),
    path('returnkey/', views.returnkey_view, name='returnkey'),
    path('fetch-substack-rss/', fetch_substack_rss, name='fetch-substack-rss'),
    path('robots.txt', views.robots_view, name='robots_txt'),
    path('sitemap/', views.sitemap_view, name='sitemap'),
    path('tokobox/', views.tokobox_view, name='tokobox'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'  # Namespace for the users app

urlpatterns = [
    path('check_email_registered/', views.check_email_registered_view, name='check_email_registered'),
    path('check_password_strength/', views.check_password_strength_view, name='check_password_strength'),
    path('check_password_valid/', views.check_password_valid_view, name='check_password_valid'),
    path('check_username_registered/', views.check_username_registered_view, name='check_username_registered'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('password_change/', views.password_change_view, name='password_change'),
    path('password-reset/', views.password_reset_view, name='password_reset'),
    path('password-reset-confirmation/', views.password_reset_confirmation_view, name='password_reset_confirmation'),
    path('profile/', views.profile_view, name='profile'),
    path('register/', views.register_view, name='register'),
    path('register_confirmation/', views.register_confirmation_view, name='register_confirmation'),
]

personal_website/models.py
from django.db import models

# Create your models here.

personal_website/forms/custom_fields.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.phonenumber import to_python
import re



# Custom validator 1: Ensure user input does not contain prohibited chars. 
allowed_input_letters_lower = 'a-z'
allowed_input_letters_upper = 'A-Z'
allowed_input_numbers = '0-9'
allowed_input_symbols_strict = '-.@_ :'
allowed_input_symbols_phone = '+-. ()+ext'





def regex_strict(user_input, allowed_input_letters_lower, allowed_input_letters_upper, allowed_input_numbers, allowed_input_symbols_strict ):
# Step 1: Define regex
# Escape the symbols for safe inclusion in regex pattern
    allowed_input_symbols_escaped = re.escape(allowed_input_symbols_strict)
    allowed_input_all = ''.join([allowed_input_letters_lower, 
                                    allowed_input_letters_upper,
                                    allowed_input_numbers, 
                                    allowed_input_symbols_escaped])
    # Regular expression pattern to match the entire string
    allowed_chars_check_pattern = r'^[' + allowed_input_all + r']+$'

# Step 2: Check if user_input matches regex returns True if no prohibited chars.
    if not re.match(allowed_chars_check_pattern, str(user_input)):
        print(f'running allowed_chars_validator...  failed for input: {user_input}')
        raise ValidationError(f'Error: Allowed characters include: { allowed_input_letters_lower}, { allowed_input_letters_upper}, { allowed_input_numbers}, and { allowed_input_symbols_strict }')
    print(f'running allowed_chars_validator...  passed for input: {user_input}')



def regex_phone(user_input, allowed_input_letters_lower, allowed_input_letters_upper, allowed_input_numbers, allowed_input_symbols_phone):
# Step 1: Define regex
# Escape the symbols for safe inclusion in regex pattern
    allowed_input_symbols_escaped = re.escape(allowed_input_symbols_phone)
    allowed_input_all = ''.join([allowed_input_numbers, 
                                    allowed_input_symbols_escaped])
    # Regular expression pattern to match the entire string
    allowed_chars_check_pattern = r'^[' + allowed_input_all + r']+$'

# Step 2: Check if user_input matches regex returns True if no prohibited chars.
    if not re.match(allowed_chars_check_pattern, str(user_input)):
        print(f'running allowed_chars_validator...  failed for input: {user_input}')
        raise ValidationError(f'Error: Allowed characters include: { allowed_input_numbers}, and { allowed_input_symbols_phone }')
    print(f'running allowed_chars_validator...  passed for input: {user_input}')





# EmailField plus:
# - forces user input to lowercase
# - trims input
#
class EmailFieldLowerRegexStrict(forms.EmailField):
    def clean(self, user_input):
        user_input = super().clean(user_input)  # Perform the standard cleaning and validation first
        user_input = user_input.lower().strip()
        regex_strict(user_input, allowed_input_letters_lower, allowed_input_letters_upper, 
        allowed_input_numbers, allowed_input_symbols_strict)
        return user_input


# CharField: plus
# - trims input
# - Strict regex
class CharFieldRegexStrict(forms.CharField):
    def clean(self, user_input):
        user_input = super().clean(user_input)  # Perform the standard cleaning and validation first
        user_input = user_input.strip()
        regex_strict(user_input, allowed_input_letters_lower, allowed_input_letters_upper, 
        allowed_input_numbers, allowed_input_symbols_strict)
        return user_input



# CharField: plus
# - trims input
# - TitleCases input
# - Strict regex
class CharFieldTitleCaseRegexStrict(forms.CharField):
    def clean(self, user_input):
        user_input = super().clean(user_input)  # Perform the standard cleaning and validation first
        user_input = user_input.title().strip()
        regex_strict(user_input, allowed_input_letters_lower, allowed_input_letters_upper, 
        allowed_input_numbers, allowed_input_symbols_strict)
        return user_input

# CharField: plus
# - trims input
# - TitleCases input
class CharFieldRegexPhone(PhoneNumberField):
    def clean(self, value):
        phone_number = to_python(value)
        if phone_number and not phone_number.is_valid():
            raise forms.ValidationError('Error: Please enter a valid phone number.')
        
        phone_number_str = str(phone_number.national_number)
        regex_phone(phone_number_str, allowed_input_letters_lower, allowed_input_letters_upper, 
        allowed_input_numbers, allowed_input_symbols_phone)
        return super().clean(value)

personal_website/forms/forms.py
from .custom_fields import CharFieldRegexPhone, CharFieldRegexStrict, CharFieldTitleCaseRegexStrict, EmailFieldLowerRegexStrict
from django import forms
from phonenumber_field.formfields import PhoneNumberField


class ContactForm(forms.Form):
    name = CharFieldTitleCaseRegexStrict(
        label='Name:',
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'Your name here', 
        'class': 'form-control', 
        'autofocus': 'autofocus'}))

    email = EmailFieldLowerRegexStrict(
        label='Email address:', 
        max_length=100,
        widget=forms.EmailInput(attrs={'placeholder': 'emailaddress@example.com',
        'class': 'form-control'}))
    
    
    phone = PhoneNumberField(
        label='Phone number, inc. country code:',
        widget=forms.TextInput(attrs={'placeholder': '+62 8XXXXXXXXXX', 'class': 'form-control'})
    )

    
    body = CharFieldRegexStrict(
        label='Message:', 
        max_length= 2000,
        min_length= 5,
        widget=forms.Textarea(attrs={'rows': 3, 
        'placeholder': 'A hot dog is absolutely a sandwich. Convince me otherwise.',
        'class': 'form-control'}))

personal_website/views.py
import base64
from django.contrib import messages
from django.core.cache import cache
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView
from .forms.forms import ContactForm
from .helpers import configure_logging, datetime, dnr_email_address, PROJECT_NAME, get_country_code, info_email_address, logging, os, Path, requests, send_email
from google.oauth2 import service_account
from googleapiclient.discovery import build
from email.mime.text import MIMEText
import os
import xml.etree.ElementTree as ET
#import phonenumbers
#from phonenumbers import geocoder


# Configures logger
logger = logging.getLogger(__name__)

# Construct the path to the .env file
env_path = Path('.') / '.' / '.env'
logger.debug(f'env_path is: { env_path }')


# View that handles CSP violation reporting 
@csrf_exempt
@require_POST
def csp_violation_report(request):
    # Process report
    return JsonResponse({'status': 'ok'})


# View to that performs an HTTP request to the substack API. Used to bypass CORS issues.
def fetch_substack_rss(request):
    logger.debug(f'running fetch_substack_rss() ... function started')
    
    
    #  Static cache key for the RSS feed.
    cache_key = 'substack_rss_feed'
    cached_data = cache.get(cache_key)
    
    if cached_data:
        logger.debug('Serving from cache')
        return JsonResponse({'articles': cached_data})


    # If not in cache, fetch the data
    target_url = 'https://matthewmcdonnell.substack.com/feed'
    logger.debug(f'running fetch_substack_rss() ... target_url is: { target_url }')
    
    try:
        response = requests.get(target_url)
    
        # If there is an ok response from the RSS feed url, do the following...
        if response.status_code == 200:
            logger.debug(f'running fetch_substack_rss() ... response from target url was: { response.status_code }')

            # Namespaces are required to correctly parse elements like dc:creator
            namespaces = {
                'dc': 'http://purl.org/dc/elements/1.1/'
            }

            root = ET.fromstring(response.content)
            items = root.findall('.//item')

            # Forward the request to the Substack API
            number_of_articles = 3

            articles = []
            for item in items[:number_of_articles]:  # Limiting to the first 3 articles
                title = item.find('title').text
                description = item.find('description').text
                link = item.find('link').text
                pubDate = item.find('pubDate').text
                # Extracting author name using the namespace dictionary
                author = item.find('dc:creator', namespaces).text if item.find('dc:creator', namespaces) is not None else "Unknown"
                enclosure = item.find('enclosure')
                image = enclosure.get('url') if enclosure is not None else None

                articles.append({
                    'title': title,
                    'description': description,
                    'link': link,
                    'pubDate': pubDate,
                    'author': author,  # Author name extracted from dc:creator
                    'image': image,
                })
                
            # Cache the data for future requests
            cache.set(cache_key, articles, timeout=300)  # Cache for 5 minutes
            logger.debug('Data fetched and cached')
            return JsonResponse({'articles': articles})

        # If the substack RSS does not return 200    
        else:
            logger.error('Failed to fetch RSS feed')
            return JsonResponse({'error': 'Failed to fetch RSS feed'}, status=500)

    except requests.RequestException as e:
        return JsonResponse({'error': str(e)}, status=500)

# Readiness check (needed for serving via GCP)
def readiness_check(request):
    
    logger.debug(f'starting readiness_check() ... ')

    # Perform any necessary checks here, such as database connectivity,
    # availability of external services, etc.
    # For simplicity, this example assumes the app is always ready.

    #try:
        # Your check logic here
        # For example: check_database_connection()
        #logger.info("Readiness check passed")
    #except Exception as e:
        #logger.error(f"Readiness check failed: {e}")
        #return HttpResponse('Service Unavailable', status=503)

    logger.debug(f'ended readiness_check() ... ')
    return HttpResponse('Ready', status=200)



# Create your views here.
def index_view(request):
    logger.debug(f'starting index() ... ')
    logger.debug(f'ending index() ... ')
    return render(request, 'personal_website/index.html')


#---------------------------------------------------------------------------

def contact_view(request):
    print(f'running contact() ... starting view')
    logger.info(f'running contact() ... starting view')

    # Handle if method = post
    if request.method == 'POST':
        print(f'starting contact() ... method is POST')
        logger.info(f'starting contact() ... method is POST')


        # Instantiate the form with POST data
        form = ContactForm(request.POST)
        print(f'running contact() ... method is POST and form is: { form }')
        logger.info(f'running contact() ... method is POST and form is: { form }')
        
        # Handle if method = post + form is valid
        if form.is_valid():
            logger.info(f'running contact() ... method is POST and form passes validation')

            try:
                # Take in data from form
                name = request.POST['name']
                email = request.POST['email']
                phone = request.POST['phone']
                body = request.POST['body']
                logger.debug(f'running contact() ... name is { name }')
                logger.debug(f'running contact() ... email is { email }')
                logger.debug(f'running contact() ... phone is { phone }')
                logger.debug(f'running contact() ... body is { body }')

                # Pull in data from .env
                sender = os.getenv('EMAIL_ADDRESS_INFO')
                recipient = os.getenv('EMAIL_ADDRESS_INFO')
                logger.debug(f'running contact() ... sender is { sender }')
                logger.debug(f'running contact() ... recipient is { recipient }')
                
                # Populate the required fields for send_email()
                subject = 'New mattmcdonnell.net contact form submission'
                attachments = None
                body = f'''Sender name: { name }
Sender email address: { email }
Sender phone: { phone }
Message body: { body }
Message timestamp: { datetime.now() }

Thank you,
{ PROJECT_NAME }-bot at your service!
'''

                send_email(body=body, recipient=recipient, sender=sender, subject=subject)                
                messages.success(request, 'Your message has been sent. Thank you!')
                return redirect('personal_website:index')
            
            except ValueError as e:
                print(f'running contact_view ... Error: {e}  Displaying error message and contact.html ')
                messages.error(request, 'Please complete all required fields and try again')
                return render(request, 
                'personal_website/contact.html', 
                {'form': form})
        
        # Handle if method = post BUT form is invalid
        else:
            logger.error(f'running contact() ... form is invalid. Errors: {form.errors}')
            messages.error(request, 'Please correct the errors below and try again.')
            return render(request, 
            'personal_website/contact.html', 
            {'form': form})

    # Handle if method is GET
    else:
        # Que up form
        form = ContactForm()
        # For GET requests: render the html with the form
        return render(request, 'personal_website/contact.html', {'form': form})
    

def returnkey_view(request):
    return render(request, 'personal_website/returnkey.html')

def robots_view(request):
    return render(request, 'personal_website/robots.txt', content_type='text/plain')

def sitemap_view(request):
    return render(request, 'personal_website/sitemap.html')

def tokobox_view(request):
    return render(request, 'personal_website/tokobox.html')

personal_website/templates/personal_website/contact.html
{% extends 'personal_website/layout.html' %}
{% load static %}

{% block title %}
<title>Matthew McDonnell: Contact</title>
<link rel='canonical' href='https://mattmcdonnell.net/contact'/>
<meta name='description' content='Contact page for Matthew McDonnell, CFA. Part of Matthew McDonnell, CFA homepage.'>
{% endblock %}

{% block main %}
<!-- Contact Form Section -->
<section class='section' id='contact_form'>
    <div class='container-fluid text-start'>
        <div class='row'>
            <div class='col-sm-8 text-start'>
                <h5>Please complete the form below to contact me. I'd love to hear from you!</h5>
                <div class='container_contact'>
                    <form method='post'>
                        {% csrf_token %}
                        {{ form.non_field_errors }}

                        <!-- Add debug statements to check context values -->
                        {% if form.errors %}
                            <div class="error">Form has errors</div>
                            {{ form.errors }}
                        {% endif %}

                        
                        <!-- name -->
                        <div class="mb-3">
                            {{ form.name.label_tag }} {{ form.name }}
                            {% if form.name.errors %}
                                {% for error in form.name.errors %}
                                    <div class="error">{{ error }}</div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <!-- /name -->
                        
                        <!-- email -->
                        <div class="mb-3">
                            {{ form.email.label_tag }} {{ form.email }}
                            {% if form.email.errors %}
                                {% for error in form.email.errors %}
                                    <div class="error">{{ error }}</div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <!-- /email -->
                        
                        <!-- phone (country code and Number) -->
                        <div class="mb-3 row">
                            <div class='col-sm-12'>
                                {{ form.phone.label_tag }}
                                <div class="d-flex">
                                    {{ form.phone }}
                                </div>
                                {% if form.phone.errors %}
                                    {% for error in form.phone.errors %}
                                        <div class="error">{{ error }}</div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                        <!-- /phone (country code and cumber) -->

                        <!-- body -->
                        <div class="mb-3">
                            {{ form.body.label_tag }} {{ form.body }}
                            {% if form.body.errors %}
                                {% for error in form.body.errors %}
                                    <div class="error">{{ error }}</div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <!-- /body -->

                        <button type='submit' class='btn btn-primary'>Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

personal_website/templates/personal_website/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" itemscope itemtype="https://schema.org/Organization">

    <head>
        <!-- google analytics tag (gtag.js) and JS -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-62CJ8QX96T"></script>
        <script src='{% static "personal_website/javascript/googleAnalytics.js" %}'></script>
        <!-- /google analytics tag (gtag.js) and JS -->

        <!-- general settings -->
        <meta charset='utf-8'>
        <meta name='viewport' content='initial-scale=1, width=device-width'>
        <meta itemprop="logo" content='{% static "personal_website/assets/profile_logo.jpg" %}'>
        <meta itemprop='image' content='{% static "personal_website/assets/profile_logo.jpg" %}'>
        <meta itemprop='name' content='Matt McDonnell'>
        <link rel='icon' type='image/x-icon' href='{% static "personal_website/assets/profile_logo.jpg" %}'>
        <!-- general settings -->

        <!-- boostrap and custom CSS and Javascript -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <link rel='stylesheet' href='{% static "personal_website/css/styles.css" %}'>
        <script  src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        <!-- /bootstrap and custom CSS and Javascript -->
        
        <!-- jinja: title -->
        {% block title %}
        {% endblock %}
        <!-- /jinja: title -->        
    </head>

    <body>

        <!-- navbar -->
        <nav class='navbar navbar-dark bg-dark navbar-expand-lg' id='navbar'>
            <div class='container-fluid'>
                
                <!-- navbar brand -->
                <a class='navbar-brand' href='{% url "personal_website:index" %}'>
                    <img src='{% static "personal_website/assets/profile_logo.jpg" %}' alt='profile logo' class='navbar-fixed-height-img'>
                    Matthew McDonnell, CFA
                </a>
                <!-- /navbar brand -->

                <!-- navbar button to be shown on collapse -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
        
                <!-- collapsing navbar content -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    
                    <!-- left-aligned collapsing navbar content -->
                    <ul class="navbar-nav">    
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href='{% url "personal_website:index" %}'>Home</a>
                        </li>
                        <li class='nav-item dropdown'>
                            <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-bs-toggle='dropdown' aria-expanded='false'>
                                Portfolio
                            </a>
                            <ul class='dropdown-menu' aria-labelledby='navbarDropdown'>
                                <li><a class='dropdown-item' href='{% url "brokerage:index" %}' target='_blank'>MyFinance50</a></li>
                                <!--
                                <li><a class='dropdown-item' href='#'>SavorScript</a></li>
                                <li><hr class='dropdown-divider'></li>
                                <li><a class='dropdown-item' href='#'>WIP project</a></li>
                                -->
                            </ul>
                        </li>
                        <li class='nav-item dropdown'>
                            <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-bs-toggle='dropdown' aria-expanded='false'>
                                Companies founded
                            </a>
                            <ul class='dropdown-menu' aria-labelledby='navbarDropdown'>
                                <li><a class='dropdown-item' href='{% url "personal_website:returnkey" %}'>ReturnKey</a></li>
                                <li><a class='dropdown-item' href='{% url "personal_website:tokobox" %}'>TokoBox</a></li>
                                <li><a class='dropdown-item' href='#'>Nasgor Bang Mamat</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href='{% url "personal_website:contact" %}'>Contact me</a>
                        </li>
                    </ul>
                    <!-- /left-aligned collapsing navbar content -->
                    <ul class="navbar-nav ms-auto p-0">
                        <!-- right-aligned collapsing navbar content -->
                        <div class='ms-auto'>
                            <a href='https://www.linkedin.com/in/matthewjmcdonnell/' target='_blank'> <img class='navbar-fixed-height-logo' src='{% static "personal_website/assets/logo_linkedin.png" %}'  target='_blank' alt='LinkedIn logo'></a>
                            <a href='https://github.com/TheBuleGanteng' target='_blank'> <img class='navbar-fixed-height-logo' src='{% static "personal_website/assets/logo_github.png" %}'  target='_blank' alt='GitHub logo'></a>
                            <a href='https://www.duolingo.com/profile/TheBuleGanteng' target='_blank'> <img class='navbar-fixed-height-logo' src='{% static "personal_website/assets/logo_duolingo.png" %}' target='_blank' alt='Duolingo logo'></a>
                            <a href='https://matthewmcdonnell.substack.com/' target='_blank'> <img class='navbar-fixed-height-logo' src='{% static "personal_website/assets/logo_substack.png" %}' target='_blank' alt='Substack logo'></a>
                            <a href='https://twitter.com/mattjmcdonnell' target='_blank'> <img class='navbar-fixed-height-logo' src='{% static "personal_website/assets/logo_twitter.png" %}' target='_blank' alt='Twitter logo'></a>
                        </div>
                        <!-- right-aligned collapsing navbar content -->
                        
                    </ul>
                </div>
                
                <!-- /navbar collapsing navbar content -->
            </div>  
        </nav>
        <!-- /navbar -->

        <!-- flash message -->
        {% if messages %}
        <header>
            {% for message in messages %}
                <div class="alert {% if message.tags == 'error' %}alert-warning{% elif message.tags == 'success' %}alert-success{% elif message.tags == 'info' %}alert-primary{% elif message.tags == 'warning' %}alert-danger{% else %}alert-{{ message.tags }}{% endif %}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </header>
        {% endif %}
        <!-- /flash message -->

        <!-- main -->
        {% block main %}
        
            <!-- script that can be included on a page via use of '{{ block.super }}'-->
            {% if request.path == '/' %}
                <script  src='{% static "personal_website/javascript/substackFeed.js" %}'></script>
                <script  src='{% static "personal_website/javascript/typewriterEffect.js" %}'></script>
            {% endif %}
            <!-- /script that can be included on a page via use of '{{ block.super }}'-->        
        {% endblock %}
        <!-- /main -->
    
        <!-- footer -->
        <footer class='container-fluid fixed-bottom footer'>
            <div class='row'>
                <div class='col-10'>
                    <h6>Matthew McDonnell, CFA - 2024</h6>
                </div>
                <div class='col ms-auto text-end'>
                    <a href='{% url "personal_website:sitemap" %}' class='sitemap-link'>Site Map</a>
                    <a id='contact-link-footer' href='{% url "personal_website:contact" %}'>Contact</a>
                </div>
            </div>
        </footer>
        <!-- /footer -->

    <!-- custom JavaScript file -->
    <div class='custom-JS-scripts-in-layout m-0 p-0'>
        <script  src='{% static "personal_website/javascript/lightDarkMode.js" %}'></script>
    </div>
    <!-- /custom JavaScript file -->

    </body>

</html>

personal_website/templates/personal_website/sitemap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Site Map</title>
</head>
<body>
    <h1>Site Map</h1>
    <ul>
        <li><a href="{% url 'personal_website:index' %}">Home</a></li>
        <li><a href="{% url 'personal_website:contact' %}">Contact</a></li>
        <li><a href="{% url 'personal_website:returnkey' %}">ReturnKey</a></li>
        <li><a href="{% url 'personal_website:tokobox' %}">TokoBox</a></li>
        <li><a href="{% url 'personal_website:returnkey' %}">ReturnKey</a></li>
        <li><a href="{% url 'personal_website:sitemap' %}">Sitemap</a></li>
        <li><a href="{% url 'brokerage:index' %}">MyFinance50</a></li>
        <!-- Other links, as needed -->
    </ul>
</body>
</html>