brokerage/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

app_name = 'brokerage'  # Namespace for the users app

urlpatterns = [
    path('', lambda request: redirect('index/', permanent=False)),  # Temporary redirect to /index/
    path('index/', views.index_view, name='index'),
    path('index-detail/', views.index_detail_view, name='index_detail'),
    path('buy/', views.buy_view, name='buy'),
    path('check-shares/', views.check_valid_shares_view, name='check_valid_shares'),
    path('check-symbol/', views.check_valid_symbol_view, name='check_valid_symbol'),
    path('history/', views.history_view, name='history'),
    path('quote/', views.quote_view, name='quote'),
    path('sell/', views.sell_view, name='sell'),
]

homepage/urls.py
from django.contrib import admin
from django.urls import include, path
from personal_website.views import readiness_check
from utils.views import readiness_check_view


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('personal_website.urls', namespace='personal_website')),
    path('csp/', include('csp.urls', namespace='csp')),
    path('myfinance50/', include([
        path('', include(('brokerage.urls', 'brokerage'), namespace='brokerage')),
        path('', include(('users.urls', 'users'), namespace='users')),
    ])),
    path('readiness_check/', readiness_check, name='readiness_check'),
    path('utils/', include('utils.urls', namespace='utils')),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'  # Namespace for the users app

urlpatterns = [
    path('check_email_registered/', views.check_email_registered_view, name='check_email_registered'),
    path('check_password_strength/', views.check_password_strength_view, name='check_password_strength'),
    path('check_password_valid/', views.check_password_valid_view, name='check_password_valid'),
    path('check_username_registered/', views.check_username_registered_view, name='check_username_registered'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('password_change/', views.password_change_view, name='password_change'),
    path('password-reset/', views.password_reset_view, name='password_reset'),
    path('password-reset-confirmation/', views.password_reset_confirmation_view, name='password_reset_confirmation'),
    path('profile/', views.profile_view, name='profile'),
    path('register/', views.register_view, name='register'),
    path('register_confirmation/', views.register_confirmation_view, name='register_confirmation'),
]

users/forms/form_fields.py
from .custom_fields import *
import decimal
from django import forms
from django.core.exceptions import ValidationError
from ..models import UserProfile
__all__ = ['accounting_method', 'cash_initial', 'CustomDecimalField', 'email', 'first_name', 'last_name', 'password', 'password_confirmation', 'password_old', 'tax_loss_offsets', 'tax_rate_STCG', 'tax_rate_LTCG', 'USDTextInput', 'username', 'username_old']



class CustomDecimalField(forms.DecimalField):
    def to_python(self, value):
        try:
            # Attempt to convert comma-separated strings to Python decimal
            return decimal.Decimal(value.replace(',', ''))
        except decimal.InvalidOperation:
            raise ValidationError('Enter a valid number.')


class USDTextInput(forms.TextInput):
    def format_value(self, value):
        # Check if the value is a Decimal instance and format it
        if isinstance(value, decimal.Decimal):
            return f"${value:,.2f}"
        return value  # Return the original value if it's not a Decimal instance


accounting_method = forms.ChoiceField(
    label='Accounting method:',
    choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO')],
    initial='FIFO',
    required=False,
    widget=forms.Select(attrs={
        'class': 'select-custom',
    })
)

cash_initial = CustomDecimalField(
    label='Initial cash deposit:',
    max_digits=10,
    decimal_places=2,
    initial=decimal.Decimal("10000.00"),  # Use a Decimal for the initial value
    required=False,
    widget=USDTextInput(attrs={  # Use the custom widget
        'autocomplete': 'off',
        'class': 'form-control USD',
    })
)

email = EmailFieldLowerRegexStrict(
    label='Email address:', 
    max_length=100,
    widget=forms.EmailInput(attrs={
        'autocomplete': 'off',
        'class': 'form-control',
        #'placeholder': 'Your email address',
    })
)

first_name = CharFieldTitleCaseRegexStrict(
    label='First name:', 
    max_length=25,
    required=False,
    strip=True,
    widget=forms.TextInput(attrs={
        'autocomplete': 'off',
        'class': 'form-control',
        #'placeholder': 'Your first name',
    })
)
    
last_name = CharFieldTitleCaseRegexStrict(
    label='Last name:', 
    max_length=25,
    required=False,
    strip=True,
    widget=forms.TextInput(attrs={
        'autocomplete': 'off',
        'class': 'form-control',
        #'placeholder': 'Your last name',
    })
)

password = forms.CharField(
    label='Password:', 
    max_length=50,
    strip=True,
    widget=forms.PasswordInput(attrs={
        'autocomplete': 'off',
        'class': 'form-control',
        #'placeholder': 'Your password',
    })
)

password_confirmation = forms.CharField(
    label='Password:', 
    max_length=50,
    strip=True,
    widget=forms.PasswordInput(attrs={
        'autocomplete': 'off',
        'class': 'form-control',
        #'placeholder': 'Your password',
    })
)

password_old = forms.CharField(
    label='Current password:',
    max_length=50,
    strip=True,
    widget=forms.PasswordInput(attrs={
        'autocomplete': 'off',
        'class': 'form-control',
        #'placeholder': 'Your current password',
    })
)

tax_loss_offsets = forms.ChoiceField(
    label='Tax loss offsets:',
    choices=[('On', 'On'), ('Off', 'Off')],
    initial='On',
    required=False,
    widget=forms.Select(attrs={
        'class': 'select-custom',
    })
)

tax_rate_STCG = forms.DecimalField(
    label='Tax rate, short-term capital gains:',
    decimal_places=2,  # Number of decimal places
    initial=30.00,  # Default value
    min_value=0,  # Minimum value
    max_value=50,  # Maximum value
    required=False,  # Makes the field optional
    widget=forms.NumberInput(attrs={
        'type': 'range',  # Changes the input type to a range slider
        'step': 0.50,  # Step for the input
        'class': 'form-control-range w-75',  # Use Bootstrap's range input styling
        'min': 0,  # Minimum value
        'max': 50,  # Maximum value
    })
)

tax_rate_LTCG = forms.DecimalField(
    label='Tax rate, long-term capital gains:',
    initial=15.00,  # Default value
    min_value=0,  # Minimum value
    max_value=50,  # Maximum value
    decimal_places=2,  # Number of decimal places
    required=False,  # Makes the field optional
    widget=forms.NumberInput(attrs={
        'type': 'range',  # Changes the input type to a range slider
        'step': 0.50,  # Step for the input
        'class': 'form-control-range w-75',  # Use Bootstrap's range input styling
        'min': 0,  # Minimum value
        'max': 50,  # Maximum value
    })
)

username = CharFieldRegexStrict(
    label='Username:', 
    max_length=25,
    required=False,  # Makes the field optional
    strip=True,
    widget=forms.TextInput(attrs={
        'autocomplete': 'off',
        'class': 'form-control',
        #'placeholder': 'Your username',
        })
    )


username_old = CharFieldRegexStrict(
    label='Username:', 
    max_length=25,
    required=False,  # Makes the field optional
    strip=True,
    widget=forms.TextInput(attrs={
        'autocomplete': 'off',
        'class': 'form-control',
        #'placeholder': 'Your username',
        })
    )

users/views.py
# Provides ability to authenticate username+pw, log a user in, log a user out.
import base64
from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, get_backends, login, logout
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.http import require_http_methods
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from .forms import *
from google.oauth2 import service_account
from googleapiclient.discovery import build
from .models import UserProfile
import logging
import os
import re
import traceback
from urllib.parse import unquote
logger = logging.getLogger('django')

#-------------------------------------------------------------------------------

# Helper functions to be externalized

# Validates password strength, subject to the requirements listed below. 
pw_req_length = 4
pw_req_letter = 2
pw_req_num = 2
pw_req_symbol = 0
def check_password_strength(user_input):
    if (
        len(user_input) >= pw_req_length and 
        len(re.findall(r'[a-zA-Z]', user_input)) >= pw_req_letter and 
        len(re.findall(r'[0-9]', user_input)) >= pw_req_num and
        len(re.findall(r'[^a-zA-Z0-9]', user_input)) >= pw_req_symbol
        ):
        return True

# Get email addresses from .env
EMAIL_ADDRESS_PERSONAL= os.getenv('EMAIL_ADDRESS_PERSONAL') 
EMAIL_ADDRESS_INFO = os.getenv('EMAIL_ADDRESS_INFO')
EMAIL_ADDRESS_DNR = os.getenv('EMAIL_ADDRESS_DNR')



# Custom jinja filter: $x.xx or ($x.xx)
def filter_usd(value):
    """Format value as USD."""
    if value >= 0:
        return f"${value:,.2f}"
    else:
        return f"(${-value:,.2f})"


# Generates confirmation url that, when clicked, runs the 
def generate_confirmation_url(route, token, user):
    logger.debug(f'running users app, generate_confirmation_url(user, token) ... function started')
    
    # Encode the user's email with base64 to safely include it in the URL
    encoded_email = urlsafe_base64_encode(force_bytes(user.email))

    # This gives you the relative URL path, assuming your URL pattern expects a 'token' parameter
    relative_url = reverse(f'users:{route}')
    
    # Append the token and the encoded email as query parameters
    url_with_query_params = f"{relative_url}?token={token}&email={encoded_email}"

    # The value for MY_SITE_DOMAIN (e.g., 'www.example.com' or 'localhost:800') is defined in configs_project and then imported into settings.py
    domain = settings.MY_SITE_DOMAIN
    logger.debug(f'running users app, generate_confirmation_url(token) ... domain is: {domain}')

    # Decide the protocol based on your setup; use 'https' if your site is served over SSL/TLS
    #protocol = 'https'
    #logger.debug(f'running users app, generate_confirmation_url(token) ... protocol is: {protocol}')

    # Construct the full URL
    url = f'{domain}{url_with_query_params}'
    #url = f"{protocol}://{domain}{url_with_query_params}"
    return url

    
# Generates a nonce to work with Talisman-managed CSP
def generate_nonce():
    logger.debug('running users app, generate_nonce() ... generated nonce')
    return os.urandom(16).hex()


# Token generation for password reset and registration
def generate_unique_token(user):
    logger.debug(f'running generate_unique_token(user_id)... starting')
    
    # Note that tokens generated via PasswordResetTokenGenerator() are one-time use by default
    token_generator = PasswordResetTokenGenerator()
    token = token_generator.make_token(user)
    
    logger.debug(f'running generate_unique_token(user)... generated token')
    return token


# Get PROJECT_NAME from .env
PROJECT_NAME = os.getenv("PROJECT_NAME") 
logger.debug(f'PROJECT_NAME is: { PROJECT_NAME }')


# Queries the DB to check if user_input matches a registered email. Returns None if no match.
def retrieve_email(user_input):
    logger.debug(f'running retrieve_email(user_input) ... function started')
    user = User.objects.filter(email__iexact=user_input).first()
    logger.debug(f'running retrieve_email(user_input) ... returned user: { user }')
    return user


# Queries the DB to check if user_input matches a registered email
def retrieve_username(user_input):
    logger.debug(f'running retrieve_username(user_input) ... function started')
    return User.objects.filter(username__iexact=user_input).first()


# Send emails
def send_email(body, recipient, sender, subject):    
    logger.debug(f'running retrieve_username(user_input) ... function started')
    logger.debug(f'running retrieve_username(user_input) ... body is: { body }')
    logger.debug(f'running retrieve_username(user_input) ... recipient is: { recipient }')
    
    try:
        # Absolute path to the service account file
        SERVICE_ACCOUNT_FILE = os.path.join(os.path.dirname(__file__), '..', 'gitignored', 'gmail_access_credentials.json')

        # Define the required scope for sending emails
        SCOPES = ['https://www.googleapis.com/auth/gmail.send']

        # Use the service account to acquire credentials
        credentials = service_account.Credentials.from_service_account_file(
            SERVICE_ACCOUNT_FILE, scopes=SCOPES)

        # Specify the user to impersonate
        user_to_impersonate = 'matt@mattmcdonnell.net'
        logger.debug(f'running retrieve_username(user_input) ... user_to_impersonate is: { user_to_impersonate }')

        # Impersonate the user
        credentials = credentials.with_subject(user_to_impersonate)

        # Build the Gmail service
        service = build('gmail', 'v1', credentials=credentials)

        # Create a simple MIMEText email
        email_msg = MIMEText(body)
        email_msg['to'] = recipient  # Replace with the recipient's email address
        email_msg['from'] = sender
        email_msg['subject'] = subject

        # Encode the email message in base64
        encoded_message = base64.urlsafe_b64encode(email_msg.as_bytes()).decode()

        # Create the message body
        message_body = {'raw': encoded_message}

        # Send the email
        message = service.users().messages().send(userId='me', body=message_body).execute()
        print(f"Message Id: {message['id']}")

    except Exception as e:
        print(f"An error occurred: {e}")
        raise


# Token validation for password reset and registration
def verify_unique_token(token, user_id):
    logger.debug(f'running verify_unique_token(token, user_id) ... function starting')
    
    try:
        # Initialize the token generator
        token_generator = PasswordResetTokenGenerator()
        
        # Retrieve the user based on the provided user_id
        user = User.objects.get(pk=user_id)

        # Use the token generator to check if the token is valid for the given user
        if token_generator.check_token(user, token):
            logger.debug('Token is valid')
            return user
        else:
            logger.debug('Token is invalid or has expired')
            return None
    except User.DoesNotExist:
        logger.debug('User does not exist')
        return None
    except Exception as e:
        logger.error(f'Error during token verification: {e}')
        return None


#-------------------------------------------------------------------------------

# Returns the email if registered or otherwise, None
# Used with jsEmailValidation()
@require_http_methods(['POST'])
def check_email_registered_view(request):
    logger.debug('running users app, check_email_registered_view(request) ... view started')

    email = request.POST.get('user_input', None)
    if email:
        user = retrieve_email(email)
        # If a user object is found, return the email in the JsonResponse
        if user:
            return JsonResponse({'email': user.email})
        else:
            # If no user is found, return a response indicating the email is not taken
            return JsonResponse({'email': None})
    else:
        # If no email was provided in the request, return an error response
        return JsonResponse({'error': 'No email provided'}, status=400)

#--------------------------------------------------------------------------------

# Returns '{'result': True}' if user_input meets password requirements and '{'result': False}' if not.
@require_http_methods(["POST"])
def check_password_strength_view(request):
    logger.debug('running users app, check_password_strength_view(request) ... view started')

    password = request.POST.get('user_input', None)
    if password:
        result = check_password_strength(password)
        return JsonResponse({'result': result})
    else:
        # If no email was provided in the request, return an error response
        return JsonResponse({'error': 'No password provided'}, status=400)

#--------------------------------------------------------------------------------

# Checks if password passes custom strength requirements
# Used with jsPasswordValidation()
@require_http_methods(["POST"])
def check_password_valid_view(request):
    logger.debug('running users app, check_password_valid_view(request) ... view started')

    # Step 1: Pull in data passed in by JavaScript
    password = request.POST.get('password')
    password_confirmation = request.POST.get('password_confirmation')

    # Step 2: Initialize checks_passed array
    checks_passed = []

users/templates/users/layout.html
{% load static %}

<!DOCTYPE html>

<html lang='en'>

    <head>

        <meta charset='utf-8'>
        <meta name='viewport' content='initial-scale=1, width=device-width'>

        <!-- Boootstrap CSS http://getbootstrap.com/docs/5.1/ -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        

        <!-- Font Awesome CSS -->
        <link nonce='{{ request.csp_nonce }}' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css' rel='stylesheet'>
        
        <!-- Boootstrap and Jquery JavaScript -->
        <script nonce='{{ request.csp_nonce }}' src='https://code.jquery.com/jquery-3.3.1.slim.min.js'></script>
        
        <script nonce='{{ request.csp_nonce }}' src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        <!-- https://favicon.io/emoji-favicons/money-bag/ -->
        <link href="{% static 'favicon.ico' %}" rel="icon">

       <!-- Bootstrap + Customized CSS -->
       <link href='{% static "styles.css" %}' rel='stylesheet'>

        <!-- adds CSRF token to each page, removing need to add it to forms -->
        <meta name="csrf-token" content="{{ csrf_token }}">

        <title>MyFinance50{% block title %} {% endblock %}</title>

    </head>

    <body>

        <nav class='bg-light border navbar navbar-expand-md  sticky-top navbar-light'>
            <div class='container-fluid'>
                <a class='navbar-brand' href='{% url "brokerage:index" %}'><span class='red'>MyFinance</span><span class='yellow'>5</span><span class='green'>0</span></a>
                <button aria-controls='navbar' aria-expanded='false' aria-label='Toggle navigation' class='navbar-toggler' data-bs-target='#navbar' data-bs-toggle='collapse' type='button'>
                    <span class='navbar-toggler-icon'></span>
                </button>
                <div class='collapse navbar-collapse' id='navbar'>
                    {% if user.is_authenticated %}
                        <ul class='navbar-nav me-auto mt-2'>
                            <li class='nav-item'><a class='nav-link' href='{% url "brokerage:index" %}'>Home</a></li>
                            <li class='nav-item'><a class='nav-link' href='{% url "brokerage:quote" %}'>Research</a></li>
                            <li class='nav-item'><a class='nav-link' href='{% url "brokerage:buy" %}'>Buy</a></li>
                            <li class='nav-item'><a class='nav-link' href='{% url "brokerage:sell" %}'>Sell</a></li>
                            <li class='nav-item'><a class='nav-link' href='{% url "brokerage:history" %}'>History</a></li>
                            <li class='nav-item'><a class='nav-link' href='{% url "users:profile" %}'>Profile</a></li>
                            <li class='nav-item'><a class='nav-link' href='{% url "users:password_change" %}'>Change password</a></li>
                        </ul>
                        <ul class='navbar-nav ms-auto mt-2'>
                            <li class='nav-item'><a class='nav-link' href='{% url "users:logout" %}'>Log Out</a></li>
                        </ul>
                    {% else %}
                        <ul class='navbar-nav ms-auto mt-2'>
                            <li class='nav-item'><a class='nav-link' href='{% url "users:register" %}'>Register</a></li>
                            <li class='nav-item'><a class='nav-link' href='{% url "users:password_reset" %}'>Reset Password</a></li>
                            <li class='nav-item'><a class='nav-link' href='{% url "users:login" %}'>Log In</a></li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </nav>

        <!-- django's messages function -->
        <div>
            {% if messages %}
                
                <header>
                    <div class='alert alert-primary mb-0 text-center' role='alert'>
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                </header>
            {% endif %}
        </div>
        <!-- /django's messages function -->

        <!-- timeout modal controlled via JS -->
        {% if user.is_authenticated %}
            <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title">Timeout warning</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                        <p>You will be logged out in 5 minutes due to inactivity. Please extend your session or log out via the buttons below.</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" name='timeout-logout-button' data-logout-url="{% url 'users:logout' %}">Log out</button>
                            <button type="button" class="btn btn-success" name='timeout-extend-button' data-readiness-check-url="{% url 'readiness_check' %}">Remain logged in</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        <!-- /timeout modal controlled via JS -->

        
        {% block main %}{% endblock %}
        
        
        <footer class='footer mt-auto py-3 bg-light border-top border-dark-subtle sticky-footer'>
            <div class='container'>
                <span class='text-muted'>Market data provided by <a href='https://site.financialmodelingprep.com/developer/docs'>FMP</a></span>
            </div>
        </footer>

    </body>

    <!-- custom JavaScript file -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script nonce='{{ request.csp_nonce }}' src='{% static "myFinance50.js" %}'></script>
    <!-- /custom JavaScript file -->

</html>

users/templates/users/password_change.html
{% extends 'users/layout.html' %}

{% block title %}
    Change Password
{% endblock %}

{% block main %}
<div class='container-fluid pt-2 pb-5'>

    <!-- boostrap5 loading spinner -->
    <div id='loadingSpinner' class='d-flex align-items-center justify-content-center'>
        <div>
        <strong>Loading...</strong>
        <div class='spinner-border ms-auto' role='status' aria-hidden='true'></div>
        </div>
    </div>
    <!-- /boostrap5 loading spinner -->

    <!-- Instructional text -->
    <div class="container-fluid ps-0 mb-1">
        <div class="container-instructions-start-bold">
            Please complete all the fields below and click "submit" to change your password.
        </div>
        <div class="container-instructions-start">
            Required fields
        </div>
    </div>
    <!-- /Instructional text -->

    <!-- password_change -->
    <form action='{% url "users:password_change" %}' id='PasswordChangeForm' method='post'>
        {% csrf_token %}
        {{ form.non_field_errors }}
        
        <!-- email -->
        <div class='user_input_registration row'>
            <div class='col-sm-2 user-input-registration-label'>
                <label for='id_email' class='form-label-start-req-bold'>Email address:</label>
            </div>
            <div class='col-11 col-sm-8 col-md-6 col-lg-4'>
                {{ form.email }}
                {% if form.email.errors %}
                    <div class='text-danger mt-2'>
                        {% for error in form.email.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
        <!-- /email -->
        
        
        <!-- password_old -->
        <div class='user_input_registration row'>
            <div class='col-sm-2 user-input-registration-label'>
                <label for='id_password_old' class='form-label-start-req-bold'>Current password:</label>
            </div>
            <div class='col-sm-8 col-md-6 col-lg-4'>
                {{ form.password_old }}
                {% if form.password_old.errors %}
                    <div class='text-danger mt-2'>
                        {% for error in form.password_old.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
        <!-- /password -->
        
        
        <!-- password -->
        <div class='user_input_registration row'>
            <div class='col-sm-2 user-input-registration-label'>
                <label for='id_password' class='form-label-start-req-bold'>New password:</label>
            </div>
            <div class='col-sm-8 col-md-6 col-lg-4'>
                {{ form.password }}
                {% if form.password.errors %}
                    <div class='text-danger mt-2'>
                        {% for error in form.password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class='user-input-validation row'>
            <label class='col-sm-2 form-label-start-req-bold'></label>
            <div class='col-sm-8 col-md-6 col-lg-4 container-input-validation text-danger' id='password_validation' name='password_validation'>
                <div class='col-sm-8 col-md-6 col-lg-4 container-input-validation-pw-bullets'>
                    <span class='text-dark'>Password must:</span>
                    <ul>
                        <li id='pw_min_tot_chars_li' name='pw_min_tot_chars_li'>Include at least {{ pw_req_length }} characters total, including at least: 
                        
                        <li class="custom-bullet-secondary" id='pw_min_letters_li' name='pw_min_letters_li'>{{ pw_req_letter }} letters</li>
                        
                        <li class="custom-bullet-secondary" id='pw_min_num_li' name='pw_min_num_li'>{{ pw_req_num }} numbers</li>
                        
                        <li class="custom-bullet-secondary" id='pw_min_sym_li' name='pw_min_sym_li'>{{ pw_req_symbol }} symbols from the following list: {{ user_input_allowed_symbols }}</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /password -->
        
        <!-- password_confirmation -->
        <div class='user_input_registration row'>
            <div class='col-sm-2 user-input-registration-label'>
                <label for='id_password_confirmation' class='form-label-start-req-bold'>New password confirmation:</label>
            </div>
            <div class='col-sm-8 col-md-6 col-lg-4'>
                {{ form.password_confirmation }}
                {% if form.password_confirmation.errors %}
                    <div class='text-danger mt-2'>
                        {% for error in form.password_confirmation.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class='user-input-validation row'>
            <label class='col-sm-2 form-label-start-req-bold'></label>
            <div class='col-sm-8 col-md-6 col-lg-4 container-input-validation text-danger' id='password_confirmation_validation' name='password_confirmation_validation'>
                <div class='col-sm-8 col-md-6 col-lg-4 container-input-validation-pw-bullets'>
                    <span class='text-dark'>Password confirmation must:</span>
                    <ul>
                        <li id='password_confirmation_validation_match' name='password_confirmation_validation_match'>Match password</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /password_confirmation -->

        <!-- cancel and submit buttons-->
        <div class='row mb-3'>
            <div class='col-sm-6 col-md-4 col-lg-3 mt-1'>
                <a href='{% url "users:index" }' class='btn btn-secondary w-100'>Back</a>
            </div>
            <div class='col-sm-6 col-md-4 col-lg-3 mt-1'>
                <button type='submit' class='btn btn-success w-100' id='submit_button' disabled>Submit</button>
            </div>
        </div>
        <!-- /cancel and submit buttons-->

    </form>
    <!-- /Password change -->

</div>
{% endblock %}

users/templates/users/register_confirmation.html
{% extends 'users/layout.html' %}

{% block title %}
    Confirm registration
{% endblock %}

{% block main %}
    <div class='container-fluid pt-2 pb-5'>

        <!-- Instructional text -->
        <div class="container-fluid ps-0 mb-1">
            <div class="container-fluid container-instructions-start-bold">
                Thank you for confirming your registration. If you are not automatically redirected to your account, please click <a href="{{ url_for('login') }}">here</a> to login.
            </div>
        </div>
        <!-- /Instructional text -->
        
    </div>
{% endblock %}